name: Deploy Nodejs app
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout source
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
          node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies
      run: npm install  

    - name: login to docker hub 
      run : docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: build docker image 
      run : docker build -t sumedhraj957/docker-practice:main .

    - name: publish image to docker hub
      run : docker push sumedhraj957/docker-practice:main

  Deploy:
    needs: build    

    runs-on: self-hosted
    steps: 

    - name: pull image from docker hub
      run: docker pull sumedhraj957/docker-practice:main

    - name: run docker container
      run: docker run -it -d -p 6000:6000 --name node-service1 sumedhraj957/docker-practice:main

   




