name: Deploy Nodejs app
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout source
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
          node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies
      run: npm install  

    - name: login to docker hub 
      run : docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: build docker image 
      run : docker build -t sumedhraj957/docker-practice:latest .

    - name: publish image to docker hub
      run : docker push node sumedhraj957/docker-p:latest

  Deploy:
    needs: build    

    runs-on: self-hosted
    steps: 

    - name: pull image from docker hub
      run: docker pull image/nodejs-app:late

    - name: run docker container
      run: docker run -d -p 4000:4000 --name my-container 

    - name: start and run the container
      run: docker start my-container




